# QuickBoard Config Version (DO NOT TOUCH!)
qb-cfg-version: 1

# QuickBoard refresh time (in seconds), use 2 - 5 for optimal QuickBoard, increase this value if your server lag
refresh-time: 3

# QuickBoard server Query (used to request the number of players on another server)
enable: false
ip: kawaismp.net
port: 19132

# QuickBoard Title and Lines #
quickboard-title: QuickBoard
quickboard-lines:
- "Hi, Im using quickboard"
- "Lightweight dan easy to use"
- "Add more lines in config.yml"
- " "
- "Good luck"
