# QuickBoard Config Version (DO NOT TOUCH!)
qb_cfg_version: 1

# QuickBoard refresh time (in seconds), use 2 - 5 for optimal QuickBoard, increase this value if your server lag
refresh-time: 3

# QuickBoard server Query (used to request the number of players on another server)
# Use %server_query% To get the player Count
enable: false
ip: kawaismp.net
port: 19132

# QuickBoard Title and Lines #
quickboard-title: "§aQuick§eBoard"
quickboard-lines:
- "§dHi, Im using quickboard"
- "§aLightweight dan easy to use"
- "§eAdd more lines in config.yml"
- " "
- "§bGood luck"
