# QuickBoard Config Version (DO NOT TOUCH!)
qb_cfg_version: 1

# QuickBoard refresh time (in seconds), use 2 - 5 for optimal QuickBoard, increase this value if your server lag
refresh-time: 3

# QuickBoard server Query (used to request the number of players on another server)
# Use %server_query% To get the player Count
enable: false
ip: kawaismp.net
port: 19132

# QuickBoard Title and Lines #
quickboard-title: "§aQuick§eBoard"
quickboard-lines:
- "§dHi, Im using quickboard"
- "§aLightweight dan easy to use"
- "§eAdd more lines in config.yml"
- " "
- "§bGood luck"

## Avaible Plugin Placeholders
# %name%  => Get Player Name
# %display_name%  => Get Player Display Name
# %server_online%  => Count Online Players
# %max_online%  => Get Max Players From Your Server
# %server_tps%  => Get Server TPS (Tick Per Second)
# %player_ping%  => Get Player Ping
# %server_load%  => Get Server Load
# %server_query%  => Use to get Server Query 
# %item_id%  => Get item id in hand
# %player_ip%  => Get player ip
# %player_x%  => Get player X
# %player_y%  => Get player Y
# %player_z%  => Get player Z
# %player_world%  => Get Player World name
# %world_player_count%  => Get Players count in player world
# %date%  => Show date
#
## EconomyAPI Plugin
# %player_money%  => Get Player Money
#
## PurePerms Plugin
# %pp_rank% => Get Player PurePerms Rank
# %pp_prefix%  => Get Player PurePerms Prefix
# %pp_suffix%  => Get Player PurePerms Suffix
#
## FactionsPro Plugin
# %fp_faction_name%  => Get Player Faction name
# %fp_faction_power%  => Get Player Faction power
